---
- name: Add nginx signing key (Debian/Ubuntu)
  apt_key:
    url: http://nginx.org/keys/nginx_signing.key
    state: present
  when: ansible_os_family == "Debian"

- name: Add nginx repository (Ubuntu 14.04)
  apt_repository: repo={{item}} state=present update_cache=yes
  with_items:
    - 'deb http://nginx.org/packages/ubuntu/ trusty nginx'
    - 'deb-src http://nginx.org/packages/ubuntu/ trusty nginx'
  when: (ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "14")

- name: Add nginx repository (Ubuntu 16.04)
  apt_repository: repo={{item}} state=present update_cache=yes
  with_items:
    - 'deb http://nginx.org/packages/ubuntu/ xenial nginx'
    - 'deb-src http://nginx.org/packages/ubuntu/ xenial nginx'
  when: (ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "16")

- name: Add nginx repository (Debian 8)
  apt_repository: repo={{item}} state=present update_cache=yes
  with_items:
    - 'deb http://nginx.org/packages/debian/ jessie nginx'
    - 'deb-src http://nginx.org/packages/debian/ jessie nginx'
  when: (ansible_distribution == "Debian" and ansible_distribution_major_version == "8")
## There is probably a more graceful way to do this, but this works.

- name: Add nginx repository (RHEL 7)
  yum_repository:
    name: nginx
    description: nginx repo
    baseurl: http://nginx.org/packages/rhel/7/$basearch/
    gpgcheck: no
    state: present
  when: (ansible_distribution == "RedHat" and ansible_distribution_major_version == "7")

- name: Add nginx repository (RHEL 6)
  yum_repository:
    name: nginx
    description: nginx repo
    baseurl: http://nginx.org/packages/rhel/6/$basearch/
    gpgcheck: no
    state: present
  when: (ansible_distribution == "RedHat" and ansible_distribution_major_version == "6")

- name: Add nginx repository (CentOS 7)
  yum_repository:
    name: nginx
    description: nginx repo
    baseurl: http://nginx.org/packages/centos/7/$basearch/
    gpgcheck: no
    state: present
  when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "7")

- name: Add nginx repository (CentOS 6)
  yum_repository:
    name: nginx
    description: nginx repo
    baseurl: http://nginx.org/packages/centos/6/$basearch/
    gpgcheck: no
    state: present
  when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "6")
