---
- name: ensure packages are installed
  apt: name={{item}}
  with_items:
    - postgresql
    - libpq-dev
    - python-psycopg2

- name: ensure database is created
  become: true
  become_user: postgres
  vars:
    ansible_ssh_pipelining: true
  postgresql_db:
    name: "{{ db_name }}"

- name: ensure user has access to database
  become: yes
  become_user: postgres
  vars:
    ansible_ssh_pipelining: true
  postgresql_user:
    db: "{{ db_name }}"
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    priv: ALL

- name: ensure user does not have unnecessary privilege
  become: yes
  become_user: postgres
  vars:
    ansible_ssh_pipelining: true
  postgresql_user: 
    name: "{{ db_user }}"
    role_attr_flags: NOSUPERUSER,NOCREATEDB
